version: "3.3"

services:
  zookeeper-test:
    container_name: zookeeper-test
    image: 'bitnami/zookeeper'
    ports:
      - '2185:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka-test:
    container_name: kafka-test
    image: 'bitnami/kafka:latest'
    ports:
      - '9095:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-test:2185
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false